//
// Copyright 2025-2026 Hans W. Uhlig. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

//! Filesystem discovery and in-memory materialization for VDS 2.0.
//!
//! This module is deliberately independent of [`crate::storage::DocumentStore`].
//! Markdown files are parsed directly into a workspace generation that can be
//! rebuilt after process restart or cache loss.

use std::collections::BTreeMap;
use std::fmt;
use std::fs;
use std::io;
use std::path::{Component, Path, PathBuf};

use glob::Pattern;
use sha2::{Digest, Sha256};

use crate::document::{Document, DocumentId, Section, SectionId, SectionVersion};
use crate::markdown::{ParsedMarkdown, SectionSourceSpan, parse_markdown_str};
use crate::metadata::{ManagedDocumentMetadata, MetadataError, MetadataRepository};

const HARD_EXCLUDED_DIRECTORIES: &[&str] = &[".git", ".vds", ".vds2-staging"];

/// One Markdown file discovered beneath a workspace root.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct DiscoveredMarkdown {
    /// Canonical VDS path using `/` separators and relative to the workspace.
    pub relative_path: String,
    /// Host path used to read the file.
    pub absolute_path: PathBuf,
}

/// One current document generation materialized from an authoritative file.
#[derive(Clone, Debug)]
pub struct MaterializedDocument {
    /// Canonical workspace-relative source path.
    pub relative_path: String,
    /// Current document record generated by the Markdown parser.
    pub document: Document,
    /// Current section tree, including the synthetic root section.
    pub sections: Vec<Section>,
    /// Initial versions generated for the current parse generation.
    ///
    /// These are ephemeral for unmanaged documents. Durable managed history
    /// will be supplied by the `.vds` metadata repository in a later phase.
    pub versions: Vec<SectionVersion>,
    /// Whether durable `.vds` metadata was reconciled into this generation.
    pub managed: bool,
    /// Whether current Markdown matches the hash recorded by managed metadata.
    /// This is `true` for unmanaged documents because there is no durable base
    /// state against which to report an external edit.
    pub source_matches_metadata: bool,
    /// Byte-offset spans locating each non-root section within the source file.
    /// Available only while the workspace generation is current; spans become
    /// stale after any mutation and must be reloaded.
    pub source_spans: std::collections::BTreeMap<SectionId, SectionSourceSpan>,
}

impl MaterializedDocument {
    fn from_parsed(relative_path: String, parsed: ParsedMarkdown) -> Self {
        Self {
            relative_path,
            document: parsed.document,
            sections: parsed.sections,
            versions: parsed.versions,
            managed: false,
            source_matches_metadata: true,
            source_spans: parsed.source_spans,
        }
    }
}

/// An immutable current-generation view of all discovered Markdown documents.
#[derive(Clone, Debug)]
pub struct WorkspaceState {
    root: PathBuf,
    documents_by_path: BTreeMap<String, MaterializedDocument>,
    paths_by_id: BTreeMap<DocumentId, String>,
}

impl WorkspaceState {
    /// Discovers and materializes the current Markdown workspace in memory.
    pub fn load(root: impl AsRef<Path>) -> Result<Self> {
        let root = canonical_workspace_root(root.as_ref())?;
        let catalog = if root.join(".vds/workspace.json").exists() {
            Some(
                MetadataRepository::open(&root)
                    .map_err(WorkspaceError::Metadata)?
                    .load_catalog()
                    .map_err(WorkspaceError::Metadata)?,
            )
        } else {
            None
        };
        let mut documents_by_path = BTreeMap::new();
        let mut paths_by_id = BTreeMap::new();

        for discovered in discover_markdown(&root)? {
            let markdown = fs::read_to_string(&discovered.absolute_path)
                .map_err(|source| WorkspaceError::io(&discovered.absolute_path, source))?;
            let name = document_name(&discovered.relative_path);
            let parsed =
                parse_markdown_str(name, Some(discovered.relative_path.clone()), &markdown);
            let mut materialized =
                MaterializedDocument::from_parsed(discovered.relative_path.clone(), parsed);
            if let Some(metadata) = catalog
                .as_ref()
                .and_then(|catalog| catalog.document_by_path(&discovered.relative_path))
            {
                reconcile_managed_document(&mut materialized, metadata, markdown.as_bytes());
            }
            paths_by_id.insert(
                materialized.document.id.clone(),
                discovered.relative_path.clone(),
            );
            documents_by_path.insert(discovered.relative_path, materialized);
        }

        // Second pass: managed documents whose file was renamed externally won't
        // match by path above.  For each managed ID not yet placed in paths_by_id,
        // scan the unmanaged discovered documents and look for a content-hash
        // match.  When found, retroactively reconcile the document in memory and
        // persist the updated path pointer so future loads find it by path.
        if let Some(ref catalog) = catalog {
            let repo = MetadataRepository::open(&root).ok();
            for metadata in catalog.documents() {
                let id = &metadata.document.document_id;
                if paths_by_id.contains_key(id) {
                    continue;
                }
                let expected_hash = &metadata.current.content_hash;
                // Find an unmanaged document whose on-disk content matches.
                let matched_path = documents_by_path
                    .iter()
                    .filter(|(_, d)| !d.managed)
                    .find(|(path, _)| {
                        let abs = root.join(path_from_vds(path));
                        sha256(&fs::read(abs).unwrap_or_default()) == *expected_hash
                    })
                    .map(|(p, _)| p.clone());
                if let Some(new_path) = matched_path {
                    if let Some(doc) = documents_by_path.get_mut(&new_path) {
                        let content =
                            fs::read(root.join(path_from_vds(&new_path))).unwrap_or_default();
                        reconcile_managed_document(doc, metadata, &content);
                        paths_by_id.insert(id.clone(), new_path.clone());
                    }
                    // Persist the updated path so subsequent loads match by path.
                    if let Some(ref r) = repo {
                        let _ = r.record_external_rename(id, &new_path);
                    }
                }
            }
        }

        Ok(Self {
            root,
            documents_by_path,
            paths_by_id,
        })
    }

    /// Canonical host path of the workspace root.
    pub fn root(&self) -> &Path {
        &self.root
    }

    /// Current documents ordered by canonical relative path.
    pub fn documents(&self) -> impl Iterator<Item = &MaterializedDocument> {
        self.documents_by_path.values()
    }

    /// Looks up a current document by workspace-relative path.
    pub fn document_by_path(&self, relative_path: &str) -> Option<&MaterializedDocument> {
        self.documents_by_path
            .get(&normalize_separators(relative_path))
    }

    /// Looks up a current document by its generation-local identity.
    pub fn document_by_id(&self, document_id: &DocumentId) -> Option<&MaterializedDocument> {
        self.paths_by_id
            .get(document_id)
            .and_then(|path| self.documents_by_path.get(path))
    }

    /// Applies embeddings to sections across all documents.
    ///
    /// Takes a map of document_id -> (section_id -> embedding) and updates
    /// the corresponding sections in place. This is used to populate embeddings
    /// after they're generated asynchronously.
    #[cfg(all(
        feature = "semantic-search",
        any(target_os = "linux", target_os = "macos")
    ))]
    pub fn apply_embeddings(
        &mut self,
        embeddings: BTreeMap<
            DocumentId,
            BTreeMap<crate::document::SectionId, crate::document::TextEmbedding>,
        >,
    ) {
        for (doc_id, section_embeddings) in embeddings {
            if let Some(path) = self.paths_by_id.get(&doc_id)
                && let Some(doc) = self.documents_by_path.get_mut(path)
            {
                for section in &mut doc.sections {
                    if let Some(embedding) = section_embeddings.get(&section.section_id) {
                        section.embedding = Some(embedding.clone());
                    }
                }
            }
        }
    }
}

/// Discovers eligible Markdown files without parsing their contents.
pub fn discover_markdown(root: impl AsRef<Path>) -> Result<Vec<DiscoveredMarkdown>> {
    let root = canonical_workspace_root(root.as_ref())?;
    let rules = IgnoreRules::load(&root)?;
    let mut discovered = Vec::new();
    walk_directory(&root, &root, &rules, &mut discovered)?;
    discovered.sort_by(|left, right| left.relative_path.cmp(&right.relative_path));
    Ok(discovered)
}

/// Checks whether a prospective workspace-relative path is eligible for VDS
/// discovery without requiring the destination file to exist yet.
pub fn is_markdown_path_eligible(root: impl AsRef<Path>, relative_path: &str) -> Result<bool> {
    let root = canonical_workspace_root(root.as_ref())?;
    let relative_path = normalize_separators(relative_path);
    let path = Path::new(&relative_path);
    if relative_path.is_empty()
        || path.is_absolute()
        || path
            .components()
            .any(|component| !matches!(component, Component::Normal(_)))
        || path.components().any(|component| {
            component
                .as_os_str()
                .to_str()
                .is_some_and(|name| HARD_EXCLUDED_DIRECTORIES.contains(&name))
        })
        || !is_markdown_path(path)
    {
        return Ok(false);
    }
    Ok(!IgnoreRules::load(&root)?.is_ignored(&relative_path, false))
}

fn walk_directory(
    root: &Path,
    directory: &Path,
    rules: &IgnoreRules,
    discovered: &mut Vec<DiscoveredMarkdown>,
) -> Result<()> {
    let entries =
        fs::read_dir(directory).map_err(|source| WorkspaceError::io(directory, source))?;
    for entry in entries {
        let entry = entry.map_err(|source| WorkspaceError::io(directory, source))?;
        let path = entry.path();
        let file_type = entry
            .file_type()
            .map_err(|source| WorkspaceError::io(&path, source))?;

        // Symlink traversal could escape the workspace or create cycles. VDS 2
        // can add an explicit opt-in policy later.
        if file_type.is_symlink() {
            continue;
        }

        let relative = relative_vds_path(root, &path)?;
        if file_type.is_dir() {
            if is_hard_excluded_directory(&path) {
                continue;
            }
            // Ignored directories are still traversed so a later negated rule
            // can re-include a child, matching the useful part of Gitignore
            // behavior without making discovery order-dependent.
            walk_directory(root, &path, rules, discovered)?;
            continue;
        }

        if !file_type.is_file() || !is_markdown_path(&path) || rules.is_ignored(&relative, false) {
            continue;
        }

        discovered.push(DiscoveredMarkdown {
            relative_path: relative,
            absolute_path: path,
        });
    }
    Ok(())
}

fn canonical_workspace_root(root: &Path) -> Result<PathBuf> {
    let canonical = fs::canonicalize(root).map_err(|source| WorkspaceError::io(root, source))?;
    if !canonical.is_dir() {
        return Err(WorkspaceError::InvalidWorkspaceRoot(canonical));
    }
    Ok(canonical)
}

fn relative_vds_path(root: &Path, path: &Path) -> Result<String> {
    let relative = path
        .strip_prefix(root)
        .map_err(|_| WorkspaceError::PathOutsideWorkspace(path.to_path_buf()))?;
    let mut parts = Vec::new();
    for component in relative.components() {
        match component {
            Component::Normal(part) => parts.push(part.to_string_lossy().into_owned()),
            _ => return Err(WorkspaceError::InvalidRelativePath(path.to_path_buf())),
        }
    }
    Ok(parts.join("/"))
}

fn is_hard_excluded_directory(path: &Path) -> bool {
    path.file_name()
        .and_then(|name| name.to_str())
        .is_some_and(|name| HARD_EXCLUDED_DIRECTORIES.contains(&name))
}

fn is_markdown_path(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| extension.eq_ignore_ascii_case("md"))
}

fn document_name(relative_path: &str) -> String {
    Path::new(relative_path)
        .file_stem()
        .and_then(|stem| stem.to_str())
        .filter(|stem| !stem.is_empty())
        .unwrap_or("document")
        .to_owned()
}

fn reconcile_managed_document(
    document: &mut MaterializedDocument,
    metadata: &ManagedDocumentMetadata,
    markdown: &[u8],
) {
    let generated_ids = document
        .sections
        .iter()
        .map(|section| section.section_id.clone())
        .collect::<Vec<_>>();
    let sections_by_generated_id = document
        .sections
        .iter()
        .map(|section| (section.section_id.clone(), section))
        .collect::<BTreeMap<_, _>>();
    let mut id_map = BTreeMap::new();
    let mut used_durable_ids = std::collections::BTreeSet::new();

    if let Some(root) = document
        .sections
        .iter()
        .find(|section| section.parent_id.is_none())
    {
        id_map.insert(
            root.section_id.clone(),
            metadata.current.root_section_id.clone(),
        );
        used_durable_ids.insert(metadata.current.root_section_id.clone());
    }

    for section in document
        .sections
        .iter()
        .filter(|section| section.parent_id.is_some())
    {
        let ancestry = section_ancestry(section, &sections_by_generated_id);
        let content_fingerprint = sha256(section.content.as_bytes());
        let mut candidates = metadata
            .sections
            .values()
            .filter(|record| !used_durable_ids.contains(&record.section_id))
            .filter_map(|record| {
                let title_match = record.matching.last_known_title == section.title;
                let ancestry_match = record.matching.last_known_ancestry == ancestry;
                let fingerprint_match = record.matching.content_fingerprint == content_fingerprint;
                let ordinal_match = record.matching.last_known_ordinal == section.ordinal;
                let score = u8::from(fingerprint_match) * 8
                    + u8::from(title_match) * 4
                    + u8::from(ancestry_match) * 2
                    + u8::from(ordinal_match);
                (score >= 6).then_some((score, record.section_id.clone()))
            })
            .collect::<Vec<_>>();
        candidates.sort_by(|left, right| right.cmp(left));
        if let Some((best_score, best_id)) = candidates.first() {
            let unambiguous = candidates
                .get(1)
                .is_none_or(|(next_score, _)| next_score < best_score);
            if unambiguous {
                id_map.insert(section.section_id.clone(), best_id.clone());
                used_durable_ids.insert(best_id.clone());
            }
        }
    }

    for (index, section) in document.sections.iter_mut().enumerate() {
        let generated_id = &generated_ids[index];
        let durable_id = id_map
            .get(generated_id)
            .cloned()
            .unwrap_or_else(|| generated_id.clone());
        section.section_id = durable_id.clone();
        section.document_id = metadata.document.document_id.clone();
        section.parent_id = section
            .parent_id
            .as_ref()
            .map(|id| id_map.get(id).cloned().unwrap_or_else(|| id.clone()));
        section.children = section
            .children
            .iter()
            .map(|id| id_map.get(id).cloned().unwrap_or_else(|| id.clone()))
            .collect();
        if let Some(record) = metadata.sections.get(&durable_id) {
            section.current_version = record.current_version.clone();
            section.metadata = record.metadata.clone();
            section.updated_at = record.updated_at;
        }
    }

    document.source_spans = document
        .source_spans
        .iter()
        .map(|(generated_id, span)| {
            let durable_id = id_map
                .get(generated_id)
                .cloned()
                .unwrap_or_else(|| generated_id.clone());
            (durable_id, span.clone())
        })
        .collect();
    document.document.id = metadata.document.document_id.clone();
    document.document.root = metadata.current.root_section_id.clone();
    document.document.current_version = metadata.current.current_document_version.clone();
    if let Some(ref stored_name) = metadata.document.name {
        document.document.name = stored_name.clone();
    }
    document.document.metadata.title = metadata.document.title.clone();
    document.document.metadata.description = metadata.document.description.clone();
    document.document.metadata.tags = metadata.document.tags.clone();
    document.document.created_at = metadata.document.created_at;
    document.document.updated_at = metadata.current.updated_at;
    document.versions.clear();
    document.managed = true;
    document.source_matches_metadata = metadata.current.content_hash == sha256(markdown);
}

fn path_from_vds(relative_path: &str) -> PathBuf {
    relative_path.split('/').collect()
}

fn section_ancestry(
    section: &Section,
    sections_by_id: &BTreeMap<crate::document::SectionId, &Section>,
) -> Vec<String> {
    let mut titles = Vec::new();
    let mut parent_id = section.parent_id.as_ref();
    while let Some(id) = parent_id {
        let Some(parent) = sections_by_id.get(id) else {
            break;
        };
        if parent.parent_id.is_some() {
            titles.push(parent.title.clone());
        }
        parent_id = parent.parent_id.as_ref();
    }
    titles.reverse();
    titles
}

fn sha256(contents: &[u8]) -> String {
    format!("sha256:{}", hex::encode(Sha256::digest(contents)))
}

fn normalize_separators(path: &str) -> String {
    path.replace('\\', "/")
}

#[derive(Clone, Debug, Default)]
struct IgnoreRules {
    rules: Vec<IgnoreRule>,
}

impl IgnoreRules {
    fn load(root: &Path) -> Result<Self> {
        let path = root.join(".vdsignore");
        let contents = match fs::read_to_string(&path) {
            Ok(contents) => contents,
            Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(Self::default()),
            Err(source) => return Err(WorkspaceError::io(path, source)),
        };

        let mut rules = Vec::new();
        for (line_index, raw_line) in contents.lines().enumerate() {
            let line = raw_line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let (negated, pattern) = line
                .strip_prefix('!')
                .map_or((false, line), |pattern| (true, pattern));
            let pattern = normalize_separators(pattern.trim_start_matches('/'));
            let directory_prefix = pattern.strip_suffix('/').map(str::to_owned);
            let glob_text = directory_prefix.as_deref().unwrap_or(&pattern);
            let glob =
                Pattern::new(glob_text).map_err(|source| WorkspaceError::InvalidIgnorePattern {
                    path: path.clone(),
                    line: line_index + 1,
                    pattern: line.to_owned(),
                    message: source.to_string(),
                })?;
            rules.push(IgnoreRule {
                negated,
                has_separator: glob_text.contains('/'),
                directory_prefix,
                glob,
            });
        }
        Ok(Self { rules })
    }

    fn is_ignored(&self, relative_path: &str, is_directory: bool) -> bool {
        let mut ignored = false;
        for rule in &self.rules {
            if rule.matches(relative_path, is_directory) {
                ignored = !rule.negated;
            }
        }
        ignored
    }
}

#[derive(Clone, Debug)]
struct IgnoreRule {
    negated: bool,
    has_separator: bool,
    directory_prefix: Option<String>,
    glob: Pattern,
}

impl IgnoreRule {
    fn matches(&self, relative_path: &str, is_directory: bool) -> bool {
        if let Some(prefix) = &self.directory_prefix
            && (relative_path == prefix
                || relative_path
                    .strip_prefix(prefix)
                    .is_some_and(|suffix| suffix.starts_with('/')))
        {
            return true;
        }

        if self.has_separator {
            self.glob.matches(relative_path)
        } else {
            relative_path
                .split('/')
                .any(|component| self.glob.matches(component))
                || (is_directory && self.glob.matches(relative_path))
        }
    }
}

/// Filesystem and discovery errors raised while constructing a workspace.
#[derive(Debug)]
pub enum WorkspaceError {
    /// A filesystem operation failed at the named path.
    Io { path: PathBuf, source: io::Error },
    /// The configured workspace exists but is not a directory.
    InvalidWorkspaceRoot(PathBuf),
    /// A discovered path did not remain below the canonical workspace root.
    PathOutsideWorkspace(PathBuf),
    /// A relative path contained a non-normal component.
    InvalidRelativePath(PathBuf),
    /// A `.vdsignore` pattern could not be compiled.
    InvalidIgnorePattern {
        path: PathBuf,
        line: usize,
        pattern: String,
        message: String,
    },
    /// Durable `.vds` metadata could not be loaded or validated.
    Metadata(MetadataError),
    /// Another VDS writer process already holds the workspace write lease.
    Lease(crate::metadata::LeaseError),
    /// Other error with a descriptive message.
    Other(String),
}

impl WorkspaceError {
    fn io(path: impl Into<PathBuf>, source: io::Error) -> Self {
        Self::Io {
            path: path.into(),
            source,
        }
    }
}

impl fmt::Display for WorkspaceError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Io { path, source } => write!(formatter, "{}: {source}", path.display()),
            Self::InvalidWorkspaceRoot(path) => {
                write!(
                    formatter,
                    "workspace root is not a directory: {}",
                    path.display()
                )
            }
            Self::PathOutsideWorkspace(path) => {
                write!(
                    formatter,
                    "path is outside the workspace: {}",
                    path.display()
                )
            }
            Self::InvalidRelativePath(path) => {
                write!(
                    formatter,
                    "path cannot be represented by VDS: {}",
                    path.display()
                )
            }
            Self::InvalidIgnorePattern {
                path,
                line,
                pattern,
                message,
            } => write!(
                formatter,
                "invalid pattern {pattern:?} at {}:{line}: {message}",
                path.display()
            ),
            Self::Metadata(error) => write!(formatter, "metadata error: {error}"),
            Self::Lease(error) => write!(formatter, "{error}"),
            Self::Other(message) => write!(formatter, "{message}"),
        }
    }
}

impl std::error::Error for WorkspaceError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Self::Io { source, .. } => Some(source),
            Self::Metadata(error) => Some(error),
            Self::Other(_) => None,
            Self::Lease(error) => Some(error),
            _ => None,
        }
    }
}

/// Workspace result type.
pub type Result<T> = std::result::Result<T, WorkspaceError>;

#[cfg(test)]
mod tests {
    use std::time::{SystemTime, UNIX_EPOCH};

    use super::*;

    struct TestWorkspace {
        root: PathBuf,
    }

    impl TestWorkspace {
        fn new(name: &str) -> Self {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let root = std::env::temp_dir().join(format!("vds-workspace-{name}-{nonce}"));
            fs::create_dir_all(&root).unwrap();
            Self { root }
        }

        fn write(&self, relative_path: &str, contents: &str) {
            let path = self.root.join(relative_path);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(path, contents).unwrap();
        }
    }

    impl Drop for TestWorkspace {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.root);
        }
    }

    #[test]
    fn discovers_markdown_and_applies_vdsignore_in_order() {
        let workspace = TestWorkspace::new("discovery");
        workspace.write("README.md", "# Readme\n");
        workspace.write("docs/guide.MD", "# Guide\n");
        workspace.write("docs/note.txt", "not markdown\n");
        workspace.write("generated/api.md", "# Generated\n");
        workspace.write("generated/operator-guide.md", "# Operator\n");
        workspace.write(".vds/hidden.md", "# Hidden\n");
        workspace.write(".vdsignore", "generated/\n!generated/operator-guide.md\n");

        let discovered = discover_markdown(&workspace.root).unwrap();
        let paths = discovered
            .into_iter()
            .map(|document| document.relative_path)
            .collect::<Vec<_>>();

        assert_eq!(
            paths,
            vec![
                "README.md".to_owned(),
                "docs/guide.MD".to_owned(),
                "generated/operator-guide.md".to_owned(),
            ]
        );
    }

    #[test]
    fn materializes_current_documents_without_a_database() {
        let workspace = TestWorkspace::new("materialize");
        workspace.write(
            "docs/architecture.md",
            "# Architecture\n\nIntro.\n\n## Storage\n\nFilesystem first.\n",
        );

        let state = WorkspaceState::load(&workspace.root).unwrap();
        let document = state.document_by_path("docs\\architecture.md").unwrap();

        assert_eq!(document.relative_path, "docs/architecture.md");
        assert_eq!(
            document.document.metadata.source_path.as_deref(),
            Some("docs/architecture.md")
        );
        assert_eq!(document.sections.len(), 3);
        assert_eq!(document.sections[1].title, "Architecture");
        assert_eq!(document.sections[2].title, "Storage");
        assert!(state.document_by_id(&document.document.id).is_some());
    }

    #[test]
    fn validates_prospective_markdown_destinations_against_workspace_policy() {
        let workspace = TestWorkspace::new("destination-policy");
        workspace.write(".vdsignore", "archive/\n");

        assert!(is_markdown_path_eligible(&workspace.root, "docs/guide.md").unwrap());
        assert!(!is_markdown_path_eligible(&workspace.root, "archive/guide.md").unwrap());
        assert!(!is_markdown_path_eligible(&workspace.root, ".vds/guide.md").unwrap());
        assert!(!is_markdown_path_eligible(&workspace.root, "../guide.md").unwrap());
        assert!(!is_markdown_path_eligible(&workspace.root, "docs/guide.txt").unwrap());
    }

    #[test]
    fn reloads_managed_identities_and_detects_external_content_changes() {
        let workspace = TestWorkspace::new("managed-reload");
        workspace.write(
            "docs/architecture.md",
            "# Architecture\n\nIntro.\n\n## Storage\n\nFilesystem first.\n",
        );
        let initial = WorkspaceState::load(&workspace.root).unwrap();
        let initial_document = initial.document_by_path("docs/architecture.md").unwrap();
        let document_id = initial_document.document.id.clone();
        let section_ids = initial_document
            .sections
            .iter()
            .map(|section| section.section_id.clone())
            .collect::<Vec<_>>();
        MetadataRepository::initialize(&workspace.root)
            .unwrap()
            .promote(initial_document)
            .unwrap();

        let unchanged = WorkspaceState::load(&workspace.root).unwrap();
        let unchanged_document = unchanged.document_by_path("docs/architecture.md").unwrap();
        assert!(unchanged_document.managed);
        assert!(unchanged_document.source_matches_metadata);
        assert_eq!(unchanged_document.document.id, document_id);
        assert_eq!(
            unchanged_document
                .sections
                .iter()
                .map(|section| section.section_id.clone())
                .collect::<Vec<_>>(),
            section_ids
        );

        workspace.write(
            "docs/architecture.md",
            "# Architecture\n\nChanged externally.\n\n## Storage\n\nStill filesystem first.\n",
        );
        let changed = WorkspaceState::load(&workspace.root).unwrap();
        let changed_document = changed.document_by_path("docs/architecture.md").unwrap();
        assert!(changed_document.managed);
        assert!(!changed_document.source_matches_metadata);
        assert_eq!(changed_document.document.id, document_id);
        assert_eq!(
            changed_document
                .sections
                .iter()
                .map(|section| section.section_id.clone())
                .collect::<Vec<_>>(),
            section_ids
        );
    }
}
